### PR TITLE
Add Linux builds

### PR DESCRIPTION
**Pull request by a1batross**
Downloaded from depot #9 that holds Linux binaries, synced with SteamDB manifest history, and put in `linux` subdirectory.

Cleaned up from non-code stuff, like `cef_gtk.pak`, font files, icons.

### CODE REVIEW

**Comment by a1batross** [comment]
By the way, this repository is too bloated. In general, it isn't a good idea to store binaries in Git, as it makes checkouts painfully slow.

Maybe migrate it to Git LFS? But I don't remember last time when I tried it or even set up.

**Comment by oxiKKK** [comment]
Hi, yes indeed, that is true. I have heard about the git LFS however i have never tried to use it personally. But yes I agree it would be a better solution.

Regarding the painful checkouts, yes, but on the other hand, this repository is not something you would contribute often to, so it's more like just a "storage" that you clone once and thats it.

Thanks for the contribution tho. By the way, what kind of linux builds did you add? Github is struggling with even displaying the commit. Did you add only binaries?

**Comment by a1batross** [comment]
>Did you add only binaries?

Yes, them and README.md in `linux` subdirectory.

**Comment by oxiKKK** [comment]
Aight thanks, merging.

**Pull request merged**
